/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgentsRouteRouteImport } from './routes/agents/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as AnalyticsTokenUsageIndexRouteImport } from './routes/analytics/token-usage/index'
import { ServerRoute as ApiTokenUsageIndexServerRouteImport } from './routes/api/token-usage/index'
import { ServerRoute as ApiHealthIndexServerRouteImport } from './routes/api/health/index'
import { ServerRoute as ApiCustomersIndexServerRouteImport } from './routes/api/customers/index'
import { ServerRoute as ApiTokenUsageTrackServerRouteImport } from './routes/api/token-usage/track'
import { ServerRoute as ApiTokenUsageSummaryServerRouteImport } from './routes/api/token-usage/summary'
import { ServerRoute as ApiTokenUsageSummariesServerRouteImport } from './routes/api/token-usage/summaries'
import { ServerRoute as ApiTokenUsageByModelServerRouteImport } from './routes/api/token-usage/by-model'
import { ServerRoute as ApiSignalsTrackServerRouteImport } from './routes/api/signals/track'

const rootServerRouteImport = createServerRootRoute()

const AgentsRouteRoute = AgentsRouteRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRouteRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRouteRoute,
} as any)
const AnalyticsTokenUsageIndexRoute =
  AnalyticsTokenUsageIndexRouteImport.update({
    id: '/analytics/token-usage/',
    path: '/analytics/token-usage/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTokenUsageIndexServerRoute =
  ApiTokenUsageIndexServerRouteImport.update({
    id: '/api/token-usage/',
    path: '/api/token-usage/',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiHealthIndexServerRoute = ApiHealthIndexServerRouteImport.update({
  id: '/api/health/',
  path: '/api/health/',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiCustomersIndexServerRoute = ApiCustomersIndexServerRouteImport.update({
  id: '/api/customers/',
  path: '/api/customers/',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTokenUsageTrackServerRoute =
  ApiTokenUsageTrackServerRouteImport.update({
    id: '/api/token-usage/track',
    path: '/api/token-usage/track',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTokenUsageSummaryServerRoute =
  ApiTokenUsageSummaryServerRouteImport.update({
    id: '/api/token-usage/summary',
    path: '/api/token-usage/summary',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTokenUsageSummariesServerRoute =
  ApiTokenUsageSummariesServerRouteImport.update({
    id: '/api/token-usage/summaries',
    path: '/api/token-usage/summaries',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTokenUsageByModelServerRoute =
  ApiTokenUsageByModelServerRouteImport.update({
    id: '/api/token-usage/by-model',
    path: '/api/token-usage/by-model',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiSignalsTrackServerRoute = ApiSignalsTrackServerRouteImport.update({
  id: '/api/signals/track',
  path: '/api/signals/track',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/analytics/token-usage': typeof AnalyticsTokenUsageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/agents': typeof AgentsIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/analytics/token-usage': typeof AnalyticsTokenUsageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/analytics/token-usage/': typeof AnalyticsTokenUsageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/agents/$agentId'
    | '/customers/$customerId'
    | '/agents/'
    | '/analytics'
    | '/customers'
    | '/analytics/token-usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/$agentId'
    | '/customers/$customerId'
    | '/agents'
    | '/analytics'
    | '/customers'
    | '/analytics/token-usage'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/agents/$agentId'
    | '/customers/$customerId'
    | '/agents/'
    | '/analytics/'
    | '/customers/'
    | '/analytics/token-usage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRouteRoute: typeof AgentsRouteRouteWithChildren
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  AnalyticsTokenUsageIndexRoute: typeof AnalyticsTokenUsageIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/signals/track': typeof ApiSignalsTrackServerRoute
  '/api/token-usage/by-model': typeof ApiTokenUsageByModelServerRoute
  '/api/token-usage/summaries': typeof ApiTokenUsageSummariesServerRoute
  '/api/token-usage/summary': typeof ApiTokenUsageSummaryServerRoute
  '/api/token-usage/track': typeof ApiTokenUsageTrackServerRoute
  '/api/customers': typeof ApiCustomersIndexServerRoute
  '/api/health': typeof ApiHealthIndexServerRoute
  '/api/token-usage': typeof ApiTokenUsageIndexServerRoute
}
export interface FileServerRoutesByTo {
  '/api/signals/track': typeof ApiSignalsTrackServerRoute
  '/api/token-usage/by-model': typeof ApiTokenUsageByModelServerRoute
  '/api/token-usage/summaries': typeof ApiTokenUsageSummariesServerRoute
  '/api/token-usage/summary': typeof ApiTokenUsageSummaryServerRoute
  '/api/token-usage/track': typeof ApiTokenUsageTrackServerRoute
  '/api/customers': typeof ApiCustomersIndexServerRoute
  '/api/health': typeof ApiHealthIndexServerRoute
  '/api/token-usage': typeof ApiTokenUsageIndexServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/signals/track': typeof ApiSignalsTrackServerRoute
  '/api/token-usage/by-model': typeof ApiTokenUsageByModelServerRoute
  '/api/token-usage/summaries': typeof ApiTokenUsageSummariesServerRoute
  '/api/token-usage/summary': typeof ApiTokenUsageSummaryServerRoute
  '/api/token-usage/track': typeof ApiTokenUsageTrackServerRoute
  '/api/customers/': typeof ApiCustomersIndexServerRoute
  '/api/health/': typeof ApiHealthIndexServerRoute
  '/api/token-usage/': typeof ApiTokenUsageIndexServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/signals/track'
    | '/api/token-usage/by-model'
    | '/api/token-usage/summaries'
    | '/api/token-usage/summary'
    | '/api/token-usage/track'
    | '/api/customers'
    | '/api/health'
    | '/api/token-usage'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/signals/track'
    | '/api/token-usage/by-model'
    | '/api/token-usage/summaries'
    | '/api/token-usage/summary'
    | '/api/token-usage/track'
    | '/api/customers'
    | '/api/health'
    | '/api/token-usage'
  id:
    | '__root__'
    | '/api/signals/track'
    | '/api/token-usage/by-model'
    | '/api/token-usage/summaries'
    | '/api/token-usage/summary'
    | '/api/token-usage/track'
    | '/api/customers/'
    | '/api/health/'
    | '/api/token-usage/'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSignalsTrackServerRoute: typeof ApiSignalsTrackServerRoute
  ApiTokenUsageByModelServerRoute: typeof ApiTokenUsageByModelServerRoute
  ApiTokenUsageSummariesServerRoute: typeof ApiTokenUsageSummariesServerRoute
  ApiTokenUsageSummaryServerRoute: typeof ApiTokenUsageSummaryServerRoute
  ApiTokenUsageTrackServerRoute: typeof ApiTokenUsageTrackServerRoute
  ApiCustomersIndexServerRoute: typeof ApiCustomersIndexServerRoute
  ApiHealthIndexServerRoute: typeof ApiHealthIndexServerRoute
  ApiTokenUsageIndexServerRoute: typeof ApiTokenUsageIndexServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRouteRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRouteRoute
    }
    '/analytics/token-usage/': {
      id: '/analytics/token-usage/'
      path: '/analytics/token-usage'
      fullPath: '/analytics/token-usage'
      preLoaderRoute: typeof AnalyticsTokenUsageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/token-usage/': {
      id: '/api/token-usage/'
      path: '/api/token-usage'
      fullPath: '/api/token-usage'
      preLoaderRoute: typeof ApiTokenUsageIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/health/': {
      id: '/api/health/'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/customers/': {
      id: '/api/customers/'
      path: '/api/customers'
      fullPath: '/api/customers'
      preLoaderRoute: typeof ApiCustomersIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/token-usage/track': {
      id: '/api/token-usage/track'
      path: '/api/token-usage/track'
      fullPath: '/api/token-usage/track'
      preLoaderRoute: typeof ApiTokenUsageTrackServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/token-usage/summary': {
      id: '/api/token-usage/summary'
      path: '/api/token-usage/summary'
      fullPath: '/api/token-usage/summary'
      preLoaderRoute: typeof ApiTokenUsageSummaryServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/token-usage/summaries': {
      id: '/api/token-usage/summaries'
      path: '/api/token-usage/summaries'
      fullPath: '/api/token-usage/summaries'
      preLoaderRoute: typeof ApiTokenUsageSummariesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/token-usage/by-model': {
      id: '/api/token-usage/by-model'
      path: '/api/token-usage/by-model'
      fullPath: '/api/token-usage/by-model'
      preLoaderRoute: typeof ApiTokenUsageByModelServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/signals/track': {
      id: '/api/signals/track'
      path: '/api/signals/track'
      fullPath: '/api/signals/track'
      preLoaderRoute: typeof ApiSignalsTrackServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AgentsRouteRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteRouteChildren: AgentsRouteRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteRouteWithChildren = AgentsRouteRoute._addFileChildren(
  AgentsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRouteRoute: AgentsRouteRouteWithChildren,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  AnalyticsTokenUsageIndexRoute: AnalyticsTokenUsageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSignalsTrackServerRoute: ApiSignalsTrackServerRoute,
  ApiTokenUsageByModelServerRoute: ApiTokenUsageByModelServerRoute,
  ApiTokenUsageSummariesServerRoute: ApiTokenUsageSummariesServerRoute,
  ApiTokenUsageSummaryServerRoute: ApiTokenUsageSummaryServerRoute,
  ApiTokenUsageTrackServerRoute: ApiTokenUsageTrackServerRoute,
  ApiCustomersIndexServerRoute: ApiCustomersIndexServerRoute,
  ApiHealthIndexServerRoute: ApiHealthIndexServerRoute,
  ApiTokenUsageIndexServerRoute: ApiTokenUsageIndexServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
